server:
  port: 8888
  servlet:
    context-path : /report
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    - local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/wvms
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  pid :
    file : report-api.pid
  h2:
    console:
      enabled: false
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: false
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 10MB
      max-file-size: 12MB

file:
  upload-dir : /Users/we/workspace/vms-report-api/files/image
  report-template-file : report_template/template.docx
  report-result-dir : /Users/we/workspace/vms-report-api/files/report

logging:
  config: classpath:logback.xml

cross:
  origin-url : http://localhost:3000

wkms:
  key: dev-vms-report-api
  token : 10412b099832011162af7f2c497552f1dc87c8d0
  url : keyinfo-nd-dev.wemakeprice.kr
  crypto-key : wmp_common_cryptokey
  crypto-key-token : f3d5a14b87e15abc3e52d7f9bbdd9ca69b37920d