server:
  port: 8887

spring:
  profiles:
    - stg
  datasource:
    url: jdbc:mysql://172.19.30.164:3306/wvms?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
      show-sql : true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: false
  pid:
    file: report-api.pid

wkms:
  key: stg-vms-report-api
  token : 0e09c9378689fb0d20fee503f26db5d00861892e
  url : keyinfo-nd-stg.wemakeprice.kr
  crypto-key: wmp_common_cryptokey
  crypto-key-token: bc6c14b37637067cd8fd5671a5d2dcb18cbb82ce
file:
  upload-dir : /data/app/files
  report-template-dir: report_template/header.docx
  report-result-dir: /Users/sn/workspace/vms-report-api/files/report
cross:
  origin-url : http://172.19.30.164:8887
