server:
  port: 8888
  servlet:
    context-path : /report
spring:
  profiles:
    - local
  datasource:
    url: jdbc:mysql://localhost:13306/wvms?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root-pass
  pid :
    file : report-api.pid
  h2:
    console:
      enabled: false
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: false
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 10MB
      max-file-size: 12MB

file:
  upload-dir : /Users/sn/workspace/vms-report-api/files/image
  report-template-file : report_template/header.docx
  report-result-dir : /Users/sn/workspace/vms-report-api/files/report

logging:
  config: classpath:logback.xml

cross:
  origin-url : http://localhost:3000

wkms:
  key: dev-vms-report-api
  token : 10412b099832011162af7f2c497552f1dc87c8d0
  url : keyinfo-nd-dev.wemakeprice.kr
  crypto-key : wmp_common_cryptokey
  crypto-key-token : f3d5a14b87e15abc3e52d7f9bbdd9ca69b37920d