server:
  port: 8888

spring:
  profiles:
    - local
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/vms?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  pid :
    file : report-api.pid

#  datasource:
#    url: jdbc:h2:./db/vms;MODE=MYSQL;database_to_upper=false
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    initialization-mode: always
#  h2:
#    console:
#      enabled: true
#      path: /h2-console/



  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql : true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: false


logging:
  config: classpath:logback.xml