server:
  port: 8887
  servlet:
    context-path: /report
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    - dev
  datasource:
    url: jdbc:postgresql://10.107.11.63:5432/wvms
    driver-class-name:  org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
      show-sql : false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: false
  pid:
    file: report-api.pid

wkms:
  key: dev-vms-report-api
  token : 10412b099832011162af7f2c497552f1dc87c8d0
  url : keyinfo-nd-dev.wemakeprice.kr
  crypto-key: wmp_common_cryptokey
  crypto-key-token: f3d5a14b87e15abc3e52d7f9bbdd9ca69b37920d

file:
  upload-dir : /data/app/files/image
  report-template-file: report_template/template.docx
  report-result-dir: /data/app/files/report

cross:
  origin-url : http://10.107.11.63:8887