server:
  port: 8888
  servlet:
    context-path : /report
spring:
  profiles:
    - local
  datasource:
    url: jdbc:mysql://localhost:13306/wvms?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root-pass
  pid :
    file : report-api.pid
  h2:
    console:
      enabled: false
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: false
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 10MB
      max-file-size: 12MB

file:
  upload-dir : /Users/sn/workspace/vms-report-api/files
  report-template-dir : none
  report-reuslt-dir : none

logging:
  config: classpath:logback.xml

cross:
  origin-url : http://localhost:3000