server:
  port: 8887

spring:
  profiles:
    - dev
  datasource:
    url: jdbc:mysql://10.107.11.63:3306/wvms?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
      show-sql : true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.provider_disables_autocommit: false
  pid:
    file: report-api.pid

wkms:
  key: dev-vms-report-api
  token : 10412b099832011162af7f2c497552f1dc87c8d0
  url : keyinfo-nd-dev.wemakeprice.kr
  crypto-key: wmp_common_cryptokey
  crypto-key-token: f3d5a14b87e15abc3e52d7f9bbdd9ca69b37920d

file:
  upload-dir : /data/app/files
  report-template-dir: none
  report-result-dir: /Users/sn/workspace/vms-report-api/files/report

cross:
  origin-url : http://10.107.11.63:8887