
### 리포트 생성 (이미지 업로드 제외)
POST http://localhost:8888/report/api/v1/report
Content-Type: application/json
Authorization: Token 966d45aef9f67b7db4cd8fee545a1f71a4015887

{
  "diagnosis_table_id": 204,
  "general_review": "총평 작성란",
  "jira_ticket_number": "TICKET-1006",
  "report_option_group_list": [
    {
      "report_option_list": [
        {
          "ordering": 1,
          "report_option_method_list": [
            {
              "method_description": "config()",
              "method_name": "환경설정 함수",
              "method_package": "com.wemakeprice.com",
              "ordering": 1
            }
          ],
          "report_v_issue": "이슈를 작성합니다.",
          "report_v_count": 10,
          "report_v_response": "잘 대응해야겠죠?",
          "v_name": "XSS 관련"
        }
      ],
      "v_item_detail_group_id": 1
    }
  ],
  "report_v_grade": "FIRST",
  "report_v_possibility": "HIGH",
  "title": "테스트 리포트"
}



### 리포트 조회

GET http://localhost:8888/report/api/v1/report?DiagnosisTableId=204
Authorization: Token 966d45aef9f67b7db4cd8fee545a1f71a4015887